version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq6
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - rab-network

networks:
  rab-network:
    driver: bridge
